### PR TITLE
Fix-Toast-Overlapping #20

### PR DESCRIPTION
**Pull request by Jenish-1235**
Fixed the overlapping of two toast messaages i.e :- 
1. Keep phone screen vertical
2. Press back again to exit.

### CODE REVIEW

**Comment by Jenish-1235** [comment]
Could you have a look at these pr too. As I had fixed toast overlapping and will close this branch, if you can merge.

**Comment by GrazianoCapelli** [comment]
@Jenish-1235 
I didn't intend to avoid the overlapping by moving one of the two toasts, I thought to hide an eventual visible toast when the user clicks "BACK" before to show the new one in the same place (as Android toasts usually do). I take some days to evaluate your solution, that is comfortable for developers but can be ugly for the UI.

**Comment by Jenish-1235** [comment]
I don't think so, as moving ui with relative constraints won't make ui ugly. Still do you have any other solution in mind?

**Comment by Jenish-1235** [comment]
Sure , I will check it out.

**Pull request closed without merging**
